# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = D:\develop_tools\cpp\cmake-3.12.1-win64-x64\bin\cmake.exe

# The command to remove a file.
RM = D:\develop_tools\cpp\cmake-3.12.1-win64-x64\bin\cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = E:\sophimp\handcraft\code\graphics

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = E:\sophimp\handcraft\code\graphics

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	D:\develop_tools\cpp\cmake-3.12.1-win64-x64\bin\cmake-gui.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	D:\develop_tools\cpp\cmake-3.12.1-win64-x64\bin\cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start E:\sophimp\handcraft\code\graphics\CMakeFiles E:\sophimp\handcraft\code\graphics\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start E:\sophimp\handcraft\code\graphics\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CLionOpenGL

# Build rule for target.
CLionOpenGL: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 CLionOpenGL
.PHONY : CLionOpenGL

# fast build rule for target.
CLionOpenGL/fast:
	$(MAKE) -f CMakeFiles\CLionOpenGL.dir\build.make CMakeFiles/CLionOpenGL.dir/build
.PHONY : CLionOpenGL/fast

OpenGL01.obj: OpenGL01.cpp.obj

.PHONY : OpenGL01.obj

# target to build an object file
OpenGL01.cpp.obj:
	$(MAKE) -f CMakeFiles\CLionOpenGL.dir\build.make CMakeFiles/CLionOpenGL.dir/OpenGL01.cpp.obj
.PHONY : OpenGL01.cpp.obj

OpenGL01.i: OpenGL01.cpp.i

.PHONY : OpenGL01.i

# target to preprocess a source file
OpenGL01.cpp.i:
	$(MAKE) -f CMakeFiles\CLionOpenGL.dir\build.make CMakeFiles/CLionOpenGL.dir/OpenGL01.cpp.i
.PHONY : OpenGL01.cpp.i

OpenGL01.s: OpenGL01.cpp.s

.PHONY : OpenGL01.s

# target to generate assembly for a file
OpenGL01.cpp.s:
	$(MAKE) -f CMakeFiles\CLionOpenGL.dir\build.make CMakeFiles/CLionOpenGL.dir/OpenGL01.cpp.s
.PHONY : OpenGL01.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... CLionOpenGL
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... OpenGL01.obj
	@echo ... OpenGL01.i
	@echo ... OpenGL01.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

